artifact_uri: /home/alexanderandrade_ec/datascience/projects/mlops_platzi/notebooks/../experiment_ml/367490351435282586/4b6648c733aa4d74ac9ae2df560f8f35/artifacts
end_time: 1717178511996
entry_point_name: ''
experiment_id: '367490351435282586'
lifecycle_stage: active
run_id: 4b6648c733aa4d74ac9ae2df560f8f35
run_name: example_1
run_uuid: 4b6648c733aa4d74ac9ae2df560f8f35
source_name: ''
source_type: 4
source_version: ''
start_time: 1717178509002
status: 3
tags: []
user_id: alexanderandrade_ec
