artifact_location: /home/alexanderandrade_ec/datascience/projects/mlops_platzi/notebooks/../experiment_ml/367490351435282586
creation_time: 1717178493877
experiment_id: '367490351435282586'
last_update_time: 1717178493877
lifecycle_stage: active
name: iris_experiment_ml_local
